export interface IMovieDetails {
    Title: String,
    Year: String,
    Rated: String,
    Released: String,
    Runtime: String,
    Genre: String,
    Director: String,
    Writer: String,
    Actors: String,
    Plot: String,
    Language: String,
    Country: String,
    Awards: String,
    Poster: String,
    Ratings: Record<string, string>[],
    imdbRating: string,
    imdbVotes: string,
    imdbID: string,
    BoxOffice: string,
}